import LogoPrueba from '../../../../../assets/icons/logro_prueba.png';

export const achievesArray = [
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
    {
        achieveId: 123456,
        achieveTitle: 'Level Master',
        achieveContent: 'Complete 5 levels with a perfect score',
        achieveIcon: LogoPrueba,
        achieveFinal: 5,
    },
];